const countries = [
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Cuba',
    'Ecuador',
    'El Salvador',
    'Granada',
    'Guatemala',
    'Honduras',
    'Jamaica',
    'México',
    'Nicaragua',
    'Paraguay',
    'Panamá',
    'Perú',
    'Puerto Rico',
    'República Dominicana',
    'Uruguay',
    'Venezuela',
]

module.exports = countries